version: '3'
services:
    postgres:
        image: postgres:alpine
        container_name: postgres-container
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5430:5432'
        volumes: 
          - ./data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./server/src/migrations/database.sql:/docker-entrypoint-initdb.d/create_tables.sql
        networks:
          - default
    backend:
        build: 
          context: ./server
          dockerfile: ./Dockerfile
        image: backend-app:1.0
        container_name: api-container
        ports:
        - '5001:5001'
        env_file: ./server/.env
        networks:
        - default
        depends_on:
        - postgres
    frontend:
        build:
          context: ./client
          dockerfile: ./Dockerfile
        image: vue-app:1.0
        container_name: client-container
        ports: 
        - '8000:8080'
        networks:
        - default
        depends_on:
        - backend
          
        

