version: '3'
services:
    postgres:
        image: postgres:alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5430:5432'
        volumes: 
          - ./data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./src/migrations/database.sql:/docker-entrypoint-initdb.d/create_tables.sql
